### ISSUE TITLE
Crash in Storage Usage

### ISSUE THREAD

**Issue by zinalili** [TGX-Android/Telegram-X#288]
Android 8.1
MIUI
Telegram X 0.25.3.1578-armeabi-v7a

When I scroll down in "Data and Storage > Storage Usage", Telegram X crashes.
Here is the bug report from MIUI reporter:

`android.content.res.Resources$NotFoundException: Drawable org.thunderdog.challegram:id/theme_color_avatar_content with resource ID #0x7f070563
Caused by: android.content.res.Resources$NotFoundException: Resource "org.thunderdog.challegram:id/theme_color_avatar_content" (7f070563) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=6 r=0x7f070563}
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:799)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:658)
	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:316)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:891)
	at android.content.res.Resources.getDrawable(Resources.java:833)
	at androidx.appcompat.widget.x0.a(Unknown Source:0)
	at s0.i$a.a(Unknown Source:0)
	at s0.i.d(SourceFile:7)
	at je.c.k(SourceFile:5)
	at je.c.g(SourceFile:1)
	at je.c.f(Unknown Source:4)
	at sd.m.r(SourceFile:38)
	at sd.m.draw(SourceFile:247)
	at ue.q0.onDraw(SourceFile:22)
	at android.view.View.draw(View.java:19337)
	at android.view.View.updateDisplayListIfDirty(View.java:18254)
	at android.view.View.draw(View.java:19052)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4301)
	at androidx.recyclerview.widget.RecyclerView.drawChild(Unknown Source:0)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4085)
	at android.view.View.draw(View.java:19345)
	at androidx.recyclerview.widget.RecyclerView.draw(SourceFile:1)
	at android.view.View.updateDisplayListIfDirty(View.java:18254)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4285)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4265)
	at android.view.View.updateDisplayListIfDirty(View.java:18203)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:678)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:684)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:792)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3162)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2962)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2500)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1482)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7122)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:983)
	at android.view.Choreographer.doCallbacks(Choreographer.java:795)
	at android.view.Choreographer.doFrame(Choreographer.java:723)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:969)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
`

**Comment by timka-123** [comment]
same on Samsung Galaxy A41, latest beta
