### ISSUE TITLE
Failed to play video

### ISSUE THREAD

**Issue by Makh-b** [TGX-Android/Telegram-X#330]
Sometimes when I open a video (videos, video messages and gifs) tgx fails to play it. It happens for every video but not everytime.

https://user-images.githubusercontent.com/66366624/219974148-70fd811f-92cb-459a-9a55-62cab21880b5.mp4

Log:

```
====== CHECKPOINT 02/20/2023 00:08:02 ======
App: 0.25.5.1590-arm64-v8a
SDK: 28 (Pie), NDK: 21 (aarch64)
Manufacturer: HUAWEI
Model: FIG-LA1
Brand: HUAWEI
Display: FIG-LA1 9.1.0.218(C185E9R1P5)
Product: FIG-LA1
Fingerprint: HUAWEI/FIG-LA1/HWFIG-H:9/HUAWEIFIG-LA1/9.1.0.218C185:user/release-keys
Screen: 2032x1080 (2.550000)
[VIDEO][ERROR][02/20/2023 00:08:02]: Unable to play video
=== Stack Trace Dump ===
Unexpected runtime error
o3.x: Unexpected runtime error
	at o3.u1.handleMessage(SourceFile:256)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:216)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1986)
	at h4.a.a(Unknown Source:0)
	at h4.i0.m(Unknown Source:2)
	at g5.l.Y1(Unknown Source:0)
	at g5.l.X1(SourceFile:75)
	at g5.l.p(SourceFile:78)
	at o3.u1.m(SourceFile:21)
	at o3.u1.H0(SourceFile:9)
	at o3.u1.G0(SourceFile:14)
	at o3.u1.handleMessage(SourceFile:122)
	... 3 more

=== Cause #1 ===
java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1986)
	at h4.a.a(Unknown Source:0)
	at h4.i0.m(Unknown Source:2)
	at g5.l.Y1(Unknown Source:0)
	at g5.l.X1(SourceFile:75)
	at g5.l.p(SourceFile:78)
	at o3.u1.m(SourceFile:21)
	at o3.u1.H0(SourceFile:9)
	at o3.u1.G0(SourceFile:14)
	at o3.u1.handleMessage(SourceFile:122)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:216)
	at android.os.HandlerThread.run(HandlerThread.java:65)

```

**Comment by meanii** [comment]
Yes, it's happens quite often

**Comment by andruska** [comment]
The problem still exists. **Some** videos don't play, only a black square is visible, but the sound works.

**Comment by remixer-dec** [comment]
Half of the videos do not work, and the button to open the video in external player does not appear on the videos that do not work...
